"""add user_type and updated_at to users

Revision ID: 4ea9b4884e7f
Revises: 02babf1282b7
Create Date: 2025-10-18 20:35:20.881511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea9b4884e7f'
down_revision: Union[str, Sequence[str], None] = '02babf1282b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('user_type', sa.Enum('user', 'vendor', name='usertype'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'user_type')
    op.drop_column('user_profiles', 'updated_at')
    op.drop_column('user_profiles', 'created_at')
    # ### end Alembic commands ###
