"""change_price_estimate_to_numeric

Revision ID: 7566ec630e2f
Revises: 1e9ef979997a
Create Date: 2026-02-23 22:04:45.613158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7566ec630e2f'
down_revision: Union[str, Sequence[str], None] = '1e9ef979997a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cravings', 'price_estimate',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               postgresql_using="price_estimate::numeric")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cravings', 'price_estimate',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
